# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import airline_pb2 as airline__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in airline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AirlineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.buyTickets = channel.unary_unary(
                '/Airline/buyTickets',
                request_serializer=airline__pb2.Tickets.SerializeToString,
                response_deserializer=airline__pb2.AirlineStatus.FromString,
                _registered_method=True)
        self.refoundTickets = channel.unary_unary(
                '/Airline/refoundTickets',
                request_serializer=airline__pb2.Tickets.SerializeToString,
                response_deserializer=airline__pb2.AirlineStatus.FromString,
                _registered_method=True)
        self.getTicketsAvailable = channel.unary_unary(
                '/Airline/getTicketsAvailable',
                request_serializer=airline__pb2.AirlineEmpty.SerializeToString,
                response_deserializer=airline__pb2.Tickets.FromString,
                _registered_method=True)


class AirlineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def buyTickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def refoundTickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTicketsAvailable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirlineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'buyTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.buyTickets,
                    request_deserializer=airline__pb2.Tickets.FromString,
                    response_serializer=airline__pb2.AirlineStatus.SerializeToString,
            ),
            'refoundTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.refoundTickets,
                    request_deserializer=airline__pb2.Tickets.FromString,
                    response_serializer=airline__pb2.AirlineStatus.SerializeToString,
            ),
            'getTicketsAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.getTicketsAvailable,
                    request_deserializer=airline__pb2.AirlineEmpty.FromString,
                    response_serializer=airline__pb2.Tickets.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Airline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Airline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Airline(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def buyTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Airline/buyTickets',
            airline__pb2.Tickets.SerializeToString,
            airline__pb2.AirlineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def refoundTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Airline/refoundTickets',
            airline__pb2.Tickets.SerializeToString,
            airline__pb2.AirlineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTicketsAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Airline/getTicketsAvailable',
            airline__pb2.AirlineEmpty.SerializeToString,
            airline__pb2.Tickets.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
