# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: airline.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'airline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rairline.proto\"&\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"#\n\x07Tickets\x12\x18\n\x07tickets\x18\x01 \x03(\x0b\x32\x07.Ticket\" \n\rAirlineStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32]\n\x07\x41irline\x12&\n\nbuyTickets\x12\x08.Tickets\x1a\x0e.AirlineStatus\x12*\n\x0erefoundTickets\x12\x08.Tickets\x1a\x0e.AirlineStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'airline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKET']._serialized_start=17
  _globals['_TICKET']._serialized_end=55
  _globals['_TICKETS']._serialized_start=57
  _globals['_TICKETS']._serialized_end=92
  _globals['_AIRLINESTATUS']._serialized_start=94
  _globals['_AIRLINESTATUS']._serialized_end=126
  _globals['_AIRLINE']._serialized_start=128
  _globals['_AIRLINE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
