# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import car_locator_pb2 as car__locator__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in car_locator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarLocatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.rent = channel.unary_unary(
                '/CarLocator/rent',
                request_serializer=car__locator__pb2.Car.SerializeToString,
                response_deserializer=car__locator__pb2.CarLocatorStatus.FromString,
                _registered_method=True)
        self.cancelRent = channel.unary_unary(
                '/CarLocator/cancelRent',
                request_serializer=car__locator__pb2.Car.SerializeToString,
                response_deserializer=car__locator__pb2.CarLocatorStatus.FromString,
                _registered_method=True)


class CarLocatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def rent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancelRent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarLocatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'rent': grpc.unary_unary_rpc_method_handler(
                    servicer.rent,
                    request_deserializer=car__locator__pb2.Car.FromString,
                    response_serializer=car__locator__pb2.CarLocatorStatus.SerializeToString,
            ),
            'cancelRent': grpc.unary_unary_rpc_method_handler(
                    servicer.cancelRent,
                    request_deserializer=car__locator__pb2.Car.FromString,
                    response_serializer=car__locator__pb2.CarLocatorStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CarLocator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CarLocator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarLocator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def rent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CarLocator/rent',
            car__locator__pb2.Car.SerializeToString,
            car__locator__pb2.CarLocatorStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancelRent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CarLocator/cancelRent',
            car__locator__pb2.Car.SerializeToString,
            car__locator__pb2.CarLocatorStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
