# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hotel_group_pb2 as hotel__group__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hotel_group_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotelGroupStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.book = channel.unary_unary(
                '/HotelGroup/book',
                request_serializer=hotel__group__pb2.Room.SerializeToString,
                response_deserializer=hotel__group__pb2.HotelGroupStatus.FromString,
                _registered_method=True)
        self.cancelBook = channel.unary_unary(
                '/HotelGroup/cancelBook',
                request_serializer=hotel__group__pb2.Room.SerializeToString,
                response_deserializer=hotel__group__pb2.HotelGroupStatus.FromString,
                _registered_method=True)


class HotelGroupServicer(object):
    """Missing associated documentation comment in .proto file."""

    def book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancelBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelGroupServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'book': grpc.unary_unary_rpc_method_handler(
                    servicer.book,
                    request_deserializer=hotel__group__pb2.Room.FromString,
                    response_serializer=hotel__group__pb2.HotelGroupStatus.SerializeToString,
            ),
            'cancelBook': grpc.unary_unary_rpc_method_handler(
                    servicer.cancelBook,
                    request_deserializer=hotel__group__pb2.Room.FromString,
                    response_serializer=hotel__group__pb2.HotelGroupStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HotelGroup', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('HotelGroup', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelGroup(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HotelGroup/book',
            hotel__group__pb2.Room.SerializeToString,
            hotel__group__pb2.HotelGroupStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancelBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/HotelGroup/cancelBook',
            hotel__group__pb2.Room.SerializeToString,
            hotel__group__pb2.HotelGroupStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
